baseURL = 'https://rotcha.kr/'
languageCode = 'ko-kr'
title = 'rotcha'
theme = 'PaperMod'

[params]
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true
TocOpen = false
description = "일상 정보, 영업시간, 생활 꿀팁을 알려드리는 rotcha 블로그"

[params.homeInfoParams]
Title = "rotcha"
Content = "Welcome"

[params.meta]
description = "일상 정보, 영업시간, 생활 꿀팁을 알려드리는 rotcha 블로그"

[[menu.main]]
name = "글목록"
url = "/archives/"
weight = 1

[[menu.main]]
name = "검색"
url = "/search/"
weight = 2

[outputs]
home = ["HTML", "RSS", "JSON"]

[minify]
disableXML = true
minifyOutput = true
